### ISSUE TITLE
Better support for Mosaic?

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1011]
I'd like to reduce the boilerplate needed to run Mosaic and make it compatible with the new [SQL front matter](https://observablehq.com/framework/sql) declarations.

Ideally I would reference a dataset (or several) with:

```yaml
---
sql:
  trips: nyc-taxi.parquet
---
```

and then call

````
```js
const vg = vgplot(sql);
```
````

where vgplot would be a known symbol (or maybe it should be called mosaic… anyway, as a supported library). This would return `vg`, a mosaic instance attached to the same DuckDB instance as the `sql` template literal.

Currently, the most concise code I can come up with is the following 6 LOC:

````
```js
import {createAPIContext, wasmConnector} from "npm:@uwdata/vgplot";

// Instantiate a Mosaic context and a database
const vg = createAPIContext();
const mc = vg.coordinator();  // use default coordinator
mc.databaseConnector(wasmConnector());

// Load the dataset into the database
const trips = await FileAttachment("nyc-taxi.parquet").url();
mc.exec([vg.loadParquet("trips", trips)]);
```
````

6 lines is not awful, but I feel it could be better integrated. Another issue with my current approach is that this is siloed from `sql`, as it loads the parquet file separately and with a different instance (even a different version) of DuckDB.

cc: @jheer I'm sure you'll have suggestions.

**Comment by jheer** [comment]
There are three Mosaic initialization steps to consider:

1. Creating an API context. This is useful if you want to isolate a plot "namespace" (standalone legends may refer to a plot by name), use a custom coordinator, and/or extend the API. However, in most cases we could skip this step and use exported vgplot methods directly (which will then use a default API context).

2. Setting the desired database connector. Mosaic currently defaults to a socket connector. One reason was to aid tree-shaking, so that DuckDB-WASM doesn't get bundled when not needed. However, having seen more usage, I'm more convinced that maybe we should use the wasm connector by default. If we make this change, that's one less init step needed here. *BUT* I'm not sure if that really helps here, as ideally we want to give Mosaic access to the same DuckDB instance that is used to load any `sql` front-matter files.

3. Loading datasets. The new `sql` yaml front matter obviates some of this need, but maybe not entirely. We may want to perform custom loading (e.g, to create a view instead of a table, to project/filter on load, or to install extensions). If such options were available via front-matter we wouldn't need a separate loading stage. The simplest way to support this initially might be to allow arbitrary queries alongside file paths (if not already possible) under the `sql` config. But I'll leave that to you all!

**Comment by jheer** [comment]
You probably already know this, but I'll mention that the Mosaic `wasmConnector()` method can accept an existing DuckDB-WASM instance, so if it is possible to retrieve the "standard" DuckDB instance on a Framework page you can pass that in directly.

**Comment by mbostock** [comment]
Thanks for the guidance, Jeff!

> as ideally we want to give Mosaic access to the same DuckDB instance that is used to load any sql front-matter files

Big 👍 to this. It’s not currently exposed, but we could easily expose the DuckDB instance as `sql._db` so that it’s available to Mosaic. And if we define `vgplot` as a built-in that depends on `sql`, then if you edit the SQL front matter it should automatically re-evaluate Mosaic as needed during preview. I’ll look at passing `wasmConnector(sql._db)`.

**Comment by jheer** [comment]
> It’s not currently exposed, but we could easily expose the DuckDB instance as `sql._db` so that it’s available to Mosaic. And if we define `vgplot` as a built-in that depends on `sql`, then if you edit the SQL front matter it should automatically re-evaluate Mosaic as needed during preview. I’ll look at passing `wasmConnector(sql._db)`.

That would be great. You'd probably want to call it like so, assuming an explicit API context (`api`):

```js
api.context.coordinator.databaseConnector(wasmConnector({ duckdb: sql._db }));
```

**Comment by mbostock** [comment]
Woot, I got it working in #1015! I still need to figure out how to make it react to changes to the SQL front matter, but we’re close, and it’s awesome how concise it is.
