### ISSUE TITLE
Paths for FileAttachment don't work using a leading slash

### ISSUE THREAD

**Issue by zachbogart** [observablehq/framework#1066]
Was having a [Slack discussion on routing](https://observable-community.slack.com/archives/C06KPR8FCE4/p1709496586037579) and am noticing that referencing a data loader in a FileAttachment doesn't work with a leading slash.

For example, if I put the example notebooks under a `demo/` folder, then the following works when running a preview:

```js
const events = FileAttachment("/data/events.json").json();
```

but it fails for me once it is deployed to Observable. I get something like `Error: File not found: /data/events.json`

Our discussion on Slack ended on imports, which do work with a leading slash, but the FileAttachment path I think still has to be referenced by a relative path. It works locally on testing, but the deployed build fails.

**Overall**: was hoping that the paths to access data loader results with FileAttachment could allow for leading-slash paths, which would help improve organization with reference to folder organization of pages.

Thanks!

**Comment by mbostock** [comment]
Confirmed that this is a bug if the project is served not at the root of a domain. (So, you can serve a project on example.com, but not under example.com/base.) Working on a fix onw.

**Comment by zachbogart** [comment]
Apologies for the ignorant question, but now that this has been merged, does that mean it is available in Framework? Do I need to reinstall the package or wait until it is added in an upcoming release? Much appreciated.

**Comment by mythmon** [comment]
Generally all changes will be available in the next release of Framework. Given our pace lately, I'd expect that to come out this week or next. If you want to get on the absolute latest version though, you can specify git or github URLs in your package.json, as documented here: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#git-urls-as-dependencies. If you do that, make sure to keep up to date with the changes on the repo, since it will include undocumented changes that might be a little buggier or incompatible with the currently released version.
