### ISSUE TITLE
Generate a single chunk of HTML

### ISSUE THREAD

**Issue by garthk** [observablehq/framework#1081]
Further to #1080, what I _really_ want is Observable to generate a single chunk of HTML I can pull into another HTML page, supporting two scenarios:

* Present an Observable workbook at its own path in my site, but with my site's template around it
* Present one specific figure or other part of that workbook as a `<figure>` or `<aside>` in another document

**Comment by mbostock** [comment]
Probably the easiest way to do this is to iframe a page that Framework generates (along with its statically-referenced assets such as imports and files). We don’t currently intend to support this use case specifically — we intend Framework to create data apps rather than standalone visualizations — so I’m going to close this issue. But in theory it should be possible to support this case by consuming the static HTML, JavaScript, etc. that Framework generates as you describe in #1082.

**Comment by mbostock** [comment]
This is now being worked on as #1084.
