### ISSUE TITLE
sql tagged templates interpolates variable names, not values

### ISSUE THREAD

**Issue by iconara** [observablehq/framework#1118]
This code ends up running `SELECT DISTINCT columnName FROM my_table` (it interpolates the name of the variable into the SQL):

```js
const columnName = 'my_column'
const rows = await sql`SELECT DISTINCT ${columnName} FROM my_table`
// runs SELECT DISTINCT columnName FROM my_table
```

I expected it to run `SELECT DISTINCT my_column FROM table` (interpolate the _value_ of columnName into the SQL). Variable interpolation seems to work this way in fenced sql blocks, and the following code also works:

```js
const columnName = 'my_column'
const rows = await sql(['SELECT DISTINCT ' + columnName + ' FROM my_table'])
// runs SELECT DISTINCT my_column FROM my_table
```

but this, again, does not

```js
const columnName = 'my_column'
const rows = await sql(['SELECT DISTINCT ', ' FROM my_table'], columnName)
// runs SELECT DISTINCT columnName FROM my_table

**Comment by mbostock** [comment]
You can’t interpolate SQL fragments into queries, you can only interpolate values. Your original query is equivalent to

```sql
SELECT DISTINCT ? FROM my_table
```

where the value of `?` is passed separately as the string value `"my_column"`. If you want to build up a SQL query dynamically (rather than just passing in dynamic values), you’ll need to construct the string yourself.
