### ISSUE TITLE
Listen for FileAttachment loading errors

### ISSUE THREAD

**Issue by sebsebmc** [observablehq/framework#1121]
There are cases where a deployed site may attempt to reference data sources that no longer exist. This currently shows up for me when I deploy a new version of a site (every ~10 minutes with GHA) and an already open page attempts to load the data source again. This results in my page being covered in `Unable to find xxxxxx.json` errors. 

Ideally there would be a way to either add a listener for these errors or to specify behavior that the page should reload or something like that.

**Comment by mbostock** [comment]
If you deploy to Observable, the deploys should be atomic (or nearly so — HTML files are updated last after assets), and assets are marked as cache-control: immutable, so this should never happen. Are you deploying to a different hosting service?

Otherwise, you can catch file attachment loads and handle this error yourself. For example:

```js
FileAttachment("file.txt").text().catch(() => console.error("unable to load file"))
```

**Comment by sebsebmc** [comment]
I've been deploying to GitHub pages, I'll try and catch the loading and see
if that fixes it.

**Comment by sebsebmc** [comment]
I can confirm that using `catch` works in my case.
