### ISSUE TITLE
Example page for lib/deck.gl

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1182]
Two possibilities:

* https://observablehq.observablehq.cloud/pangea/party/deck.gl-map.html
* https://observablehq.observablehq.cloud/pangea/party/deck.gl.html

I think the map one is better, wdyt?

Maybe @pessimistress will have a better suggestion.

Note: in both cases I see this warning, which I think comes from some inconsistency within deck.gl:
`luma.gl: Model.updateModuleSettings is deprecated. Use Model.shaderInputs.setProps()`

**Comment by mbostock** [comment]
The map example is certainly more impressive and feels more relevant. Though it would benefit from some explanation of what you are seeing. ([The original example](https://deck.gl/examples/hexagon-layer) has a color legend and some fun interactive sliders.)

We should use a data loader instead of hot loading from githubusercontent. And you could move `<div id="container" style="background: black; height: 700px"></div>` to static HTML instead of using Hypertext Literal. Might also tweak the import as:

```js
import {DeckGL, AmbientLight, GeoJsonLayer, HexagonLayer, PointLight, LightingEffect} from "npm:deck.gl";
```

**Comment by Fil** [comment]
Yes, I've noted quite a few TODOs:

- [ ] title
- [ ] color legend
- [ ] initial transition of hexagonal bars
- [ ] interaction with inputs
  - [ ] It's not yet clear to me how we can update the props (such as radius) without creating a new chart (the source example [depends on react](https://github.com/visgl/deck.gl/blob/master/website/src/examples/hexagon-layer.js)).
- [ ] tooltips
- [ ] the tweaked import doesn't work

**Comment by Pessimistress** [comment]
This is awesome! Here are links to my own observable demos and some from community members: https://deck.gl/docs/get-started/learning-resources#prototyping--sharing

The console warning about model should be resolved in the latest patch.
