### ISSUE TITLE
DuckDB WASM large file size

### ISSUE THREAD

**Issue by zookini** [observablehq/framework#1260]
## Repro

Run an sql query from a doc e.g.
````
```sql
select 1
```
````

Build
```shell
npm run build
```

Load the page from a static site. It downloads `_npm/@duckdb/duckdb-wasm@1.28.0/dist/duckdb-eh.wasm` which is over 18MB. Is this correct? The equivalent WASM file at https://duckdb.org/docs/api/wasm/overview.html is 6.4MB

**Comment by mbostock** [comment]
Yes, this is DuckDB-Wasm’s bundle, and that’s how big it is. The equivalent Wasm file from the example you linked is actually 34.6MB, which perhaps is larger because they’re using the prerelease 1.28.1-dev181.0 rather than the latest release 1.28.0.

https://shell.duckdb.org/static/wasm/duckdb-eh.7c395809b8743828320d.wasm

Note that the compressed size is 4.2MB (and 6.4MB in the case of 1.28.1-dev181.0). Getting a smaller Wasm file would depend on optimizations made by the DuckDB-Wasm team, so you might try asking over there:

https://github.com/duckdb/duckdb-wasm

**Comment by amarder** [comment]
I'm hitting this issue as well. It's a blocker for deploying on Cloudflare Pages (25MB file size limit). If anyone has clever workarounds I'd be very curious to hear them. 🙏

**Comment by amarder** [comment]
Thinking I'll move over to using SQLite, which should be fine for my needs: https://observablehq.com/framework/lib/sqlite
