### ISSUE TITLE
Resize helper doesn't work properly if preceded by an empty line or code block

### ISSUE THREAD

**Issue by ae3e** [observablehq/framework#1284]
When the resize helper is preceded by an empty line or code block, the returned width maximum is 640.
See exemple below :

The following code :

`````md
# Width test

${width}px

<div class="card">
Cell 1
${resize((width, height) => {
    return html`<div style="width:${width}px;background-color:lightblue">${width}</div>`;
})}
</div>


<div class="card">
Cell 2

${resize((width, height) => {
    return html`<div style="width:${width}px;background-color:lightblue">${width}</div>`;
})}
</div>


<div class="card">
Cell 3

```js
let div = (value)=>{
    return html`<div style="width:${value}px;background-color:lightblue">${value}</div>`;
}
```

${resize((width, height) => div(width))}
</div>


`````

![image](https://github.com/observablehq/framework/assets/12472719/894f4087-0989-44a4-932f-6a905ec26bce)

**Comment by mbostock** [comment]
This is expected because it’s wrapped in an implicit paragraph element in Markdown, and paragraphs have a max-width of 640px. You should use HTML instead if you want more control.

Also, unless the card has an explicit height set, you typically want to use the single-argument form of resize that only listens for width.

```html
<div class="card">
  <h2>Cell 2</h2>
${resize((width) => {
    return html`<div style="width:${width}px;background-color:lightblue">${width}</div>`;
})}
</div>
```
