### ISSUE TITLE
Auto-link HTML H2 elements and include them in the TOC

### ISSUE THREAD

**Issue by jm-rivera** [observablehq/framework#1292]
The [Table of contents](https://observablehq.com/framework/config#toc) supports H2 elements. However, only the markdown version `##` gets added. Any HTML `<h2></h2>` get ignored.

**Comment by mbostock** [comment]
Investigating…

The code actually does find the H2 elements. The problem is that when an H2 is specified in HTML, unlike Markdown it isn’t automatically wrapped in a header anchor; we use [markdown-it-anchor](https://github.com/valeriangalliat/markdown-it-anchor) to do that for Markdown. So the code finds the H2 elements, but then ignores them because they don’t have an `<a href class="observablehq-header-anchor">` inside.

So, you can declare a heading that is visible in the TOC like so:

```html
<h2 id="this-is-a-test" tabindex="-1">
  <a class="observablehq-header-anchor" href="#this-is-a-test">This is a test</a>
</h2>
```

(The `tabindex` attribute is optional but recommended.)

To do this automatically, we’d need to duplicate the behavior of markdown-it-anchor for HTML H2 elements: automatically wrap them in an anchor and compute a unique slug based on the text content of the heading. Another possibility is that we require you to specify the `id` attribute when specifying an H2 element in HTML (so that there is no ambiguity as to what the link should be); in general we treat HTML as a lower-level API to Markdown.

Probably this means we should not use markdown-it-anchor so we don’t have two code paths for generating heading links; instead, we let markdown-it render the `##` as a vanilla H2, and then we use the same code path for turning H2 into heading links regardless of whether it was specified as HTML or as Markdown.
