### ISSUE TITLE
keeping framework up to date

### ISSUE THREAD

**Issue by chriscooning** [observablehq/framework#1310]
We had an end user ask how to upgrade to the latest framework version — they weren't able to find information on this within our documentation and recommended adding this to docs.

reference: https://observable-community.slack.com/archives/C06KPR8FCE4/p1714982954679309

These commands are fairly common to users familiar with npm, however I can see how this might be missed by those who may not have had a lot of experience using npm.

FYI @dunstan

**Comment by mbostock** [comment]
I don’t think we should cover the basics of using npm (or Yarn or whatever package manager) in our docs.

**Comment by pettiross** [comment]
I'd like to see us add this, too. We don't need to respecify all of package management, but part of being a polyglot solution means we should be welcoming to folx whose expertise is not yet in JS development. A short article that gives the incantations for `yarn` and `npm` would make a great evergreen link from our release notes.

**Comment by mbostock** [comment]
I suggest:

* In the _Getting started_ tutorial, we should mention that `npm init @observablehq` command is actually shorthand for `npm exec @observablehq/framework -- create`. This is important because it explains that the underlying package for Framework is `@observablehq/framework`, not `@observablehq`.
* In the **Next steps** section, we can mention running `npm update` to update to the latest version of Framework.
