### ISSUE TITLE
When suggesting `--port` in Getting started, clarify that `npm run` needs `--` to pass additional arguments

### ISSUE THREAD

**Issue by anacierdem** [observablehq/framework#1355]
When I try to run the dev environment for a project initialized via `npm init "@observablehq"`, it fails with:

```
Unexpected error: listen EACCES: permission denied 127.0.0.1:3000
```

Simply because I have indeed another service running on that port. But there is no apparent way of providing an alternative port.

Official [docs](https://observablehq.com/framework/getting-started#2.-develop) suggest using `--port 3001` but it also fails with:

```
observable: Unexpected argument '3001'. This command does not take positional arguments. See 'observable help preview'.
```

Docs also mention this:

>... the preview server will choose the next available port, so your actual port may vary ...

But I doubt it does such a detection.

The way to do it is also passing an additional `--` so that parameters are passed to the underlying command properly:

```
npm run dev -- --port
```

**Comment by mbostock** [comment]
The preview server does indeed check whether the port is available here:

https://github.com/observablehq/framework/blob/d244fa19d771ebc8871f5d10edd39762c8f1b266/src/preview.ts#L80-L89

However, it’s looking for a `EADDRINUSE` error. The `EACCESS` error suggests a different issue, which is that the process doesn’t have permission to open this port. That is surprising, since normally ports >1024 are allowed to be used without needing sudo privileges. Perhaps Framework should treat both `EACCESS` and `EADDRINUSE` errors the same way?

The docs are correct here in suggesting `--port 3001`, they just fail to document `npm run`’s behavior, which is documented here:

https://docs.npmjs.com/cli/v10/commands/npm-run-script

Generally, we don’t try to duplicate the documentation of other tools in our docs because there’s too much to cover. But we could add a note about needing the `--` here.

**Comment by Fil** [comment]
@anacierdem can you give some context, like what operating system you were running? We haven't been able to reproduce an EACCES error on unprivileged ports.
