### ISSUE TITLE
Automatically add pages in a directory in the Config file without having to specify each one. 

### ISSUE THREAD

**Issue by EdwardDeaver** [observablehq/framework#1497]
It would be a nice addon to instead of having to specify each page in a directory like https://observablehq.com/framework/config#pages. 

Instead, to be able to set the directory and load the names/paths from the front-matter of the markdown inside.

So myPath/*.

**Comment by Fil** [comment]
How different is this from the default when you don't specify pages?

**Comment by EdwardDeaver** [comment]
How would do that?

_{name: "Blog", path: "/Blog/"},_

Just links to /Blog assuming there is a Blog.md file. 

I want all posts in the /Blog/ folder to automatically be loaded as a link in the pages tab under a "Blog" title. Like how the pages under "Inputs" show on https://observablehq.com/framework/ but I don't want to define them individually like https://github.com/observablehq/framework/blob/main/observablehq.config.ts#L35

**Comment by mbostock** [comment]
You get the default by not specifying the **pages** option in your config file.

**Comment by EdwardDeaver** [comment]
Ah, so I removed that and now see the page title there, but not the folder title. 

I would like it to show 

> Blog 
-- My Blog Post 1 

Currently, it's just showing

-- My Blog Post 1 

Even though the folder structure is 

>Blog > MyBlogPost1.md 

<img width="280" alt="Screenshot 2024-07-02 at 2 33 10 PM" src="https://github.com/observablehq/framework/assets/7695377/7382de4f-880c-4d65-a5df-56bd7e503289">

**Comment by mbostock** [comment]
The sidebar only supports two levels of hierarchy, so I don’t think we want to reflect the folder hierarchy in the sidebar by default. The config file is code, so you can write code that uses `fs.readdir` to generate the value of **pages** by reading a folder rather than listing them manually.

```js
export default {
  root: "docs",
  output: "docs/.observablehq/dist",
  title: "My Website",
  pages: [
    {
      name: "Inputs",
      open: false,
      pager: "inputs",
      pages: readdirSync("docs/blog").map((path) => ({
        name: readTitle(join("docs/blog", path)),
        path: `/blog/${path}`
      }))
    }
  ]
};
```

You’d have to implement your own `readTitle` function to parse the Markdown file and extract the title, though… You can see how we do that here:

https://github.com/observablehq/framework/blob/60ff015673730a8f21ea74cef22b8ed3b981782e/src/markdown.ts#L258C19-L269C2
