### ISSUE TITLE
dot does not show HTML edge labels

### ISSUE THREAD

**Issue by nichtich** [observablehq/framework#1534]
DOT syntax supports HTML labels of nodes and edges, e.g. this example graph:

~~~dot
graph {
  a [label=<<i>test</i>>];
  a -- b [label=< <i>test</i> >];
}
~~~

The graph is [shown correctly with viz](https://viz-js.com/?dot=Z3JhcGggewogIGEgW2xhYmVsPTw8aT50ZXN0PC9pPj5dOwogIGEgLS0gYiBbbGFiZWw9PCA8aT50ZXN0PC9pPiA-XTsKfQ~~) but when using in Observable

~~~
dot`graph {
  a [label=<<i>test</i>>];
  a -- b [label=< <i>test</i> >];
}`
~~~

the result is this:

![grafik](https://github.com/user-attachments/assets/7323e170-10af-4622-a6d6-21562f8b8238)

**Comment by mbostock** [comment]
This works fine in Observable Framework (this repo):

<img width="987" alt="Screenshot 2024-07-24 at 9 25 52 PM" src="https://github.com/user-attachments/assets/d89878c3-47a4-4c11-84b2-d50d5954c415">

Your screenshot suggests that you’re trying to do this in an Observable notebook, whose `dot` implementation uses an older version 2.0.0 of Viz.js. Observable Framework uses the latest version of Viz.js, which is currently 3.7.0. It looks like support for HTML labels was added in Viz.js [version 3.2.0](https://github.com/mdaines/viz-js/releases/tag/viz-release-3.2.0).

If you want to file a bug for Observable notebooks, please use the [Observable feedback repo](https://github.com/observablehq/feedback). But because Observable notebooks don’t yet support standard library versioning (unlike Observable Framework, where you can control dependency versions) it’s unlikely that we will fix this in notebooks soon.
