### ISSUE TITLE
Homebrew / whalebrew installation

### ISSUE THREAD

**Issue by abitrolly** [observablehq/framework#1545]
I've just opened the tutorial. It would be nice if Observable Framework could be installed with Homebrew, or better `whalebrew` from Docker container. To avoid Node and library version mess.

**Comment by mythmon** [comment]
We do not recommend installing Framework globally on the system, and instead suggest using a specific version for each package. The commands in the getting started guide do this by creating a new project and then installing the latest version of Python in it.

For managing Node versions, I recommend [fnm](https://github.com/Schniz/fnm) which can help install multiple versions of Node and use one per project. Unlike some other tools, library managed in Node is easier because it uses something like Python virtualenvs by default, instead of defaulting to a global system installation.

If you'd like to use Docker, you could also use something like [observablehq/framework-runtime](https://github.com/observablehq/framework-runtime) which has various system dependencies, including Node, installed. It doesn't have Framework installed though, because that shouldn't be installed globally.

**Comment by abitrolly** [comment]
@mythmon `whalebrew` runs a docker image. Any objections against container images?

**Comment by mythmon** [comment]
The "don't install globally" advice is not due to system isolation or packaging concerns. Instead it stems from a philosophy that a project's dependencies and tools should be specified within the repository that defines the other aspects of the project. The version and installation of Framework that you use is important to the way the project builds, and it shouldn't be something managed outside the repository. If anything would be installed from `whalebrew` or Homebrew it would be Node itself.

If you used `whalebrew` to install Framework, then you're still using a version of Framework that doesn't relate to the project you're building. In our experience that's prone to causing version mismatch problems, especially for tools under active development like Framework.

Further, Framework is designed to work with any tools available on your system. It can use languages like Python or Rust out of the box, and is easy to integrate with any other data processing tools on the system. From what I understand about `whalebrew`, we would be limited to tools built-in to our image. That's a limitation that would likely frustrate and confuse users that are trying to use Framework with tools that we didn't foresee them using. Including a kitchen sink of likely tools would bloat our installation. (For a concrete example, I'm working on using Zig in a project. Framework doesn't have explicit support for Zig, but it still works because it just runs binaries from my system).

I'm not opposed to containers at all, and when automating and deploying Framework projects, I reach to Docker. But I'm using Node.js base images or generic Linux images. I can then use standard language tools to install the project's dependencies such as `yarn install`, `npm install`, or similar. For daily interactive use cases, installing Framework within each project is the supported approach.

**Comment by abitrolly** [comment]
@mythmon specification of tools and dependencies in a project is orthogonal to the containerized worklow. Containerized software can fetch project deps at build time, run time, or inherit them from other container.

`whalebrew` allows to run one tool that contains sophisticated dependencies as any other executable, but without installing all its dependencies on the system. I though that Framework is static generator like Hugo - single binary that I can run to compile the framework project from source into static web site. And if my site needs newer version of Hugo - Hugo will tell me to upgrade.

Now I am not sure how Framework really works, but I prefer to experiment with containerized apps, than have a chance to destroy my system, even for an hour.
