### ISSUE TITLE
RuntimeError: Failed to fetch dynamically imported module: https://xxx.observablehq.cloud//_import/components/rangoSemanas.883616f7.js

### ISSUE THREAD

**Issue by gcoch** [observablehq/framework#1671]
The App the data uploads correctly after manual deploy, but throws this error after the first scheduled deploy.  This is happening w/ all the imported files.

**Comment by gcoch** [comment]
Seems that moving all the imports into the md pages does the trick. I've also added
localStorage.clear();
sessionStorage.clear();

**Comment by mcmcclur** [comment]
I can't help but notice that you've got two slashes in your URL:

    cloud//_import

That looks like an error, though, I'm not sure how it was produced.

**Comment by gcoch** [comment]
Hi Mark, thanks for the comment. Could've been an error when I typed the message here. The imported modules worked well locally but didn't when I deployed the code to the cloud. Since then, I moved the code to each page and it's worked. There's another issue though, which is that automated deploys are not reading the code in github branches, but instead use the master branch.

Side note: I live in Durham - not far from Asheville : - )

**Comment by mcmcclur** [comment]
I mentioned this because that double slash looks a lot like something that might arise programmatically, particularly since there's no project-name in the URL. Rather than 

    observablehq.cloud//_import/...

I'd expect

    observablehq.cloud/project-name/_import...

 It's hard to say without seeing the code but I think that might happen if you generate a link dynamically using an absolute path to pass to the `import` function. I just opened a [similar issue](https://github.com/observablehq/framework/issues/1677).
