### ISSUE TITLE
absolute URL imports aren’t correctly resolved during build

### ISSUE THREAD

**Issue by declann** [observablehq/framework#1755]
I'm importing from npm, ESM code that imports other ESM by URL reference.

Framework is rewriting those URLs so that they are invalid and I get 404s in my build.

![image](https://github.com/user-attachments/assets/773a702c-318b-4d00-99eb-dd47cd2fc6bd)

In dev mode URLs aren't rewritten and my code loads correctly.

Not sure if Framework wants to traverse remote URLs or probably just avoid rewriting them.

**Comment by mbostock** [comment]
I’m not able to reproduce this bug. If you can provide a reproduction I would be happy to reopen and investigate further. Please also include which version number of Framework you are using, and please try clearing your cache first (`npm run clean` or remove the `.observablehq/cache` directory within your source root, typically `src`).

The following npm import worked for me as expected:

````md
```js
import * as cd from "npm:calcudata-experiments";
```
````

It appears that you are using a [Node import](https://observablehq.com/framework/imports#node-imports), not an [npm import](https://observablehq.com/framework/imports#npm-imports), but that also worked as expected. First I installed `calcudata-experiments` (using Yarn because that’s my preferred package manager):

```sh
yarn add calcudata-experiments
```

````md
```js
import * as cd from "calcudata-experiments";
```
````

In both cases the generated code preserved the full URL. For example, for the Node import I saw:

```js
import*as b from"https://cdn.jsdelivr.net/npm/@tidyjs/tidy/+esm";
import*as h from"https://cdn.jsdelivr.net/npm/compassql/+esm";
```

And for the npm import I saw:

```js

import*as e from"https://cdn.jsdelivr.net/npm/@tidyjs/tidy/+esm";
import*as n from"https://cdn.jsdelivr.net/npm/compassql/+esm";
```

If there is a bug where URL imports are being corrupted, I would like to fix it, so please let me know if you (and how I) can reproduce in the current version of Framework. That said, I do not recommend baking URL imports into your code; this discourages people from self-hosting libraries and having a runtime dependency on a server they do not control (jsDelivr). The recommended pattern would be to change your code to import using a bare module specifier. So instead of this:

```js
import * as tidy from "https://cdn.jsdelivr.net/npm/@tidyjs/tidy/+esm";
import * as cql from "https://cdn.jsdelivr.net/npm/compassql/+esm";
```

You’d say:

```js
import * as tidy from "@tidyjs/tidy";
import * as cql from "compassql";
```

And you’d declare the desired versions of these two packages in the `dependencies` of your package.json file.

**Comment by mbostock** [comment]
Okay, I’m able to reproduce the problem now. It’s not a problem with the preview server, which is working correctly; it’s a problem with building the static site.
