### ISSUE TITLE
Enable autom. deployment on vercel

### ISSUE THREAD

**Issue by lukasbelka** [observablehq/framework#814]
Like with other static site generators it should be possible to deploy observable framework from a repo automatically on vercel.

**Comment by lukasbelka** [comment]
After having adjusted engine to node=18.x I tried to deploy to vercel using three different build commands from package.json but none of these worked.

**Comment by Fil** [comment]
It should be relatively straightforward to deploy static pages that you already have built on your machine—this should work on any host, since it's all static files.

However, I suppose that you are trying to have the vercel servers build the site. In that case, we want to configure that server to provide an environment that supports both build (the base requirements are: node >= 20.6 and access to npm). If you have data loaders, the environment should also contain any software that your scripts want to call (for example python with a virtual environment holding statistical packages, or duckdb, Mathematica, ffmpeg…).

I don't know exactly how this works on vercel. For a similar example, though, you can see [this Dockerfile](https://huggingface.co/spaces/observablehq/fpdn/blob/main/Dockerfile) which installs the binary for duckdb on our [hugging-face space](https://huggingface.co/spaces), then runs `yarn build`. The project is rebuilt by the hugging-face servers each time we push code to that repo (see the [public site](https://huggingface.co/spaces/observablehq/fpdn).)

If you have more specific questions or examples of things that do not work, let us know.

**Comment by lukasbelka** [comment]
Many thanks Fil, I will go through this and try it again.

**Comment by Fil** [comment]
relevant tweet by @rauchg
https://twitter.com/rauchg/status/1758339515658485941

**Comment by lukasbelka** [comment]
Ok great. For me it is fine to build it locally and push that to my repo. That's working with with vercel - many thanks for your support on that!
