### ISSUE TITLE
mime-type: "null"

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#874]
when a mime-type is unknown (for example, for ".sqlite" files), the FileAttachment(x).mimeType property is set to "null" (the string).

That's probably two issues:
- when it's not known, it should be null (the null value)—or just not a property— but not "null"
- fix this for sqlite: it should be application/vnd.sqlite3

**Comment by mbostock** [comment]
Re. application/vnd.sqlite3, that would require opening the file and inspecting the contents, since `.db` is not exclusively a SQLite file extension. And if we did that, it wouldn’t match what most static servers do (which is application/octet-stream). 

I was hoping you would get the application/vnd.sqlite3 if you switch to `.sqlite` instead, but it looks like there aren’t any file extensions registered in `mime-db` for SQLite. But I think application/octet-stream is fine in any case.
