### ISSUE TITLE
Linked assets should auto-refresh on edit

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#908]
A generalization of #415. For example if you have an `<img>` tag, we detect this a linked file; we could generate a URL with a hash, and push down the changes over the socket if the file changes.

**Comment by trebor** [comment]
#905 explicitly covers stylesheets and images.  other types i can think off the top of my head are:

  - fonts 
  - audio
  - video
  - scripts with the script tag
  - iframe for local html files

i can image fully general code that looks for `href` or `src` fields starting with the asset file name - rather than handling them one by one.

**Comment by mbostock** [comment]
This may end up colliding with #843 which affects nearly everything involving files and imports.

**Comment by trebor** [comment]
got it, maybe hold of until #843 lands.

**Comment by mbostock** [comment]
Fixed in #843.
