### ISSUE TITLE
build before replacing

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#950]
We should build in build-current/, then on success “atomically” rename build/ to build-old/ and build-current to build, and finally rimraf build-old/. This would help to compare a broken build to the previous run. I would also ensure that a build is served locally without interruption, for workflows where it makes sense to do so (like sharing with ngrok or some such).

**Comment by mbostock** [comment]
Do you mean just in our repo, or do you mean `observable build` in general? The former should be readily doable, but the latter would be a fairly significant API change since we don’t do clean builds — people could already rely on the fact that we only add files to the giving `dist` folder and preserve what’s already there.

**Comment by Fil** [comment]
I meant for `observable build` in general, but I was confused as I was experiencing this situation in our repo while testing builds repeatedly. However, it's not _needed_ in our repo, so let's do nothing.
