### ISSUE TITLE
Support dynamic page data

### ISSUE THREAD

**Issue by mootari** [observablehq/framework#982]
I'd like to derive page titles from their file names without having to generate a list of pages in the config.

From what I can tell there is currently no way to modify the data that has been extracted from a page's frontmatter because it gets parsed independently from MarkdownIt, and since the markdownIt hook has no access to the page context.

Could we consider adding a hook that receives the extracted page data and path context and returns the modified data?

**Comment by mbostock** [comment]
The config can be code — can you generate the list dynamically there? Or is the idea that you want it to affect the title in the browser window, not just the in the sidebar? Can you give more context around this use case? Why do you need to generate titles from file names, rather than say having h1 elements within the pages?

**Comment by mbostock** [comment]
I think this is already supported in the sense that you can write code in your config file, so closing. If there’s more context around the use case here, feel free to comment and we can consider reopening.
